# Generated by Django 4.1.7 on 2023-04-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='room_uuid',
            new_name='ac_uuid',
        ),
        migrations.AddField(
            model_name='ac',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='main_app.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac', to='main_app.ac'),
        ),
    ]
