# Generated by Django 4.1.7 on 2023-04-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_ac_room_remove_room_ac_ac_ac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='ac',
            new_name='room',
        ),
    ]
