# Generated by Django 4.1.7 on 2023-04-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_room_ac_alter_ac_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ac',
        ),
    ]
