# Generated by Django 4.1.7 on 2023-04-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_room_ac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='ac',
        ),
        migrations.AddField(
            model_name='ac',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.circuit'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.room'),
        ),
    ]
