# Generated by Django 4.1.7 on 2023-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_circuit_ac_ac_circuit_alter_ac_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='esp_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
