# Generated by Django 4.1.3 on 2023-04-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_ac_user_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
