# Generated by Django 4.1.3 on 2023-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_ac_name_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
