# Generated by Django 4.1.3 on 2023-05-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_userroomassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroomassign',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
