# Generated by Django 4.1.3 on 2023-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_userroomassign_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
