# Generated by Django 4.1.3 on 2023-05-16 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0018_room_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='duration',
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(blank=True, editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
