# Generated by Django 4.1.3 on 2023-05-16 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_room_duration_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroomassign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 16, 16, 6, 4, 456483, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userroomassign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
