# Generated by Django 4.1.7 on 2023-05-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_userroomassign_created_at_userroomassign_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoomAssign',
        ),
    ]
