# Generated by Django 4.1.7 on 2023-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_delete_userroomassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
