# Generated by Django 4.1.7 on 2023-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_ac_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
