# Generated by Django 4.1.7 on 2023-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='total_ac_working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
