# Generated by Django 4.1.7 on 2023-05-28 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_ac_total_ac_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='total_ac_working_hours',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
