# Generated by Django 4.1.7 on 2023-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_ac_total_ac_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
