# Generated by Django 4.1.7 on 2023-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_alter_ac_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
