# Generated by Django 4.1.7 on 2023-05-23 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_assign_duration', '0002_useracassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracassign',
            name='user',
        ),
        migrations.AddField(
            model_name='useracassign',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
