# Generated by Django 4.1.7 on 2023-05-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_delete_userroomassign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_assign_duration', '0004_alter_useracassign_ac_alter_useracassign_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracassign',
            name='ac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ac'),
        ),
        migrations.AlterField(
            model_name='useracassign',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.room'),
        ),
        migrations.AlterField(
            model_name='useracassign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
