# Generated by Django 4.1.7 on 2023-05-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_delete_userroomassign'),
        ('user_assign_duration', '0005_alter_useracassign_ac_alter_useracassign_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDurationOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('remain_duration', models.DurationField(blank=True, null=True)),
                ('is_time_over', models.BooleanField(blank=True, default=False, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.room')),
            ],
        ),
    ]
