# Generated by Django 4.1.7 on 2023-05-24 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_assign_duration', '0006_roomdurationover'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdurationover',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomdurationover',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
