# Generated by Django 4.1.7 on 2023-05-26 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_assign_duration', '0008_roomdurationover_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracassign',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useracassign',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
