# Generated by Django 4.1.7 on 2023-05-26 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_assign_duration', '0009_useracassign_endtime_useracassign_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroomassign',
            name='user',
        ),
        migrations.AddField(
            model_name='userroomassign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
