# Generated by Django 4.1.7 on 2023-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_assign_duration', '0011_userroomassign_remain_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroomassign',
            name='remain_duration',
            field=models.DurationField(blank=True, default=models.DurationField(blank=True, null=True), null=True),
        ),
    ]
