# Generated by Django 4.1.3 on 2023-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(blank=True, max_length=100)),
                ('task', models.CharField(blank=True, max_length=100)),
                ('on_by', models.CharField(blank=True, max_length=100)),
                ('off_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('on_time', models.DateTimeField(blank=True)),
                ('off_time', models.DateTimeField(blank=True)),
                ('total_on_time', models.CharField(blank=True, max_length=100)),
                ('total_ac_working_hours', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
