# Generated by Django 4.1.3 on 2023-05-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adms_logs', '0002_logs_created_at_logs_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ac_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='off_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='off_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='on_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='on_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='total_ac_working_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='total_on_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
