# Generated by Django 4.1.3 on 2023-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adms_logs', '0003_alter_logs_ac_name_alter_logs_off_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='total_ac_working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='total_on_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
