# Generated by Django 4.1.7 on 2023-07-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adms_logs', '0004_alter_logs_total_ac_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
